image: java:8-jdk

stages:
  - build
  - test
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  paths:
    - .cache/gradle/caches
    - .cache/gradle/wrapper
    
build:
  allow_failure: false
  script:
    - chmod +x ./gradlew
    - ./gradlew -g .cache/gradle clean assemble
  only:
    - master
  stage: build
 

test:
  script:
    - chmod +x ./gradlew
    - ./gradlew -g .cache/gradle check --stacktrace
  only:
    - master
  stage: test
 
deploy:
  stage: deploy
  image: ruby:2.3
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=kandoe --buildpack=heroku/ruby --api-key=18715d98-89d3-423c-afbd-3e4ad51339ec
  environment:
    name: dev
    url: https://vel-ci-api-dev.herokuapp.com
  only:
    - master
  tags:
    - docker
    - shared
  only:
   - master
  stage: deploy
